name: covid_19_statistic
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Network  
  dio: ^4.0.6
  # State Management
  get: ^4.6.5
  get_storage: ^2.0.3
  # UI utility
  flutter_screenutil: ^5.5.3+2


 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  